name: Check ready for stable

on:
  workflow_dispatch:
    inputs:
      flags:
        type: string
        required: false

  schedule:
    # * is a special character in YAML, so you have to quote this string
    # every day
    - cron:  '33 3 * * *'
  
jobs:
  ready-for-stable:
    name: check ready for stable
    if: |
      github.repository == 'iobroker-bot-orga/check-tasks'
      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
      - run: npm i
      - run: node checks/checkReadyForStable/checkReadForStable.js ${{ github.event.inputs.flags }} 
        env:
          OWN_GITHUB_TOKEN: ${{ secrets.OWN_GITHUB_TOKEN }}
          IOBBOT_GITHUB_TOKEN: ${{ secrets.IOBBOT_GITHUB_TOKEN }}
