name: Check ready for stable

on:
  workflow_dispatch:
    inputs:
      nocheck:
        type: boolean
        required: false
        default: false
        description: 'Skip triggering repository checker workflows'

      noemail:
        type: boolean
        required: false
        default: false
        description: 'Skip sending the summary report by email'

      flags:
        type: string
        required: false

  schedule:
    # * is a special character in YAML, so you have to quote this string
    # every day
    - cron:  '33 3 * * *'
  
jobs:
  ready-for-stable:
    name: check ready for stable
    if: |
      github.repository == 'iobroker-bot-orga/check-tasks'
      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - run: npm i
      - name: Trim workflow parameters
        id: trim_params
        run: |
          FLAGS=$(echo "${{ github.event.inputs.flags }}" | xargs)
          NOCHECK_ARG=""
          if [ "${{ github.event.inputs.nocheck }}" == "true" ]; then
            NOCHECK_ARG="--nocheck"
          fi
          NOEMAIL_ARG=""
          if [ "${{ github.event.inputs.noemail }}" == "true" ]; then
            NOEMAIL_ARG="--noemail"
          fi
          echo "flags=$FLAGS" >> $GITHUB_OUTPUT
          echo "nocheck_arg=$NOCHECK_ARG" >> $GITHUB_OUTPUT
          echo "noemail_arg=$NOEMAIL_ARG" >> $GITHUB_OUTPUT
      - run: node checks/checkReadyForStable/checkReadyForStable.js ${{ steps.trim_params.outputs.flags }} ${{ steps.trim_params.outputs.nocheck_arg }} ${{ steps.trim_params.outputs.noemail_arg }}
        env:
          OWN_GITHUB_TOKEN: ${{ secrets.OWN_GITHUB_TOKEN }}
          IOBBOT_GITHUB_TOKEN: ${{ secrets.IOBBOT_GITHUB_TOKEN }}
          REPORT_MAIL_SERVER: "mail.gmx.net"
          REPORT_MAIL_PORT: 465
          REPORT_MAIL_USERNAME: iobroker-bot@gmx.at
          REPORT_MAIL_PASSWORD: ${{ secrets.IOBBOT_GMXMAIL }}
          REPORT_MAIL_FROM: "ioBroker Bot"
          REPORT_MAIL_TO: "iobroker-bot@gmx.at"
