name: Check ready for stable

on:
  workflow_dispatch:
    inputs:
      nocheck:
        type: boolean
        required: false
        default: false
        description: 'Skip triggering repository checker workflows'

      noemail:
        type: boolean
        required: false
        default: false
        description: 'Skip sending the summary report by email'

      flags:
        type: string
        required: false

  schedule:
    # * is a special character in YAML, so you have to quote this string
    # every day
    - cron:  '33 3 * * *'
  
jobs:
  ready-for-stable:
    name: check ready for stable
    if: |
      github.repository == 'iobroker-bot-orga/check-tasks'
      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - run: npm i
      - name: Trim workflow parameters
        id: trim_params
        run: |
          FLAGS=$(echo "${{ github.event.inputs.flags }}" | xargs)
          NOCHECK_ARG=""
          if [ "${{ github.event.inputs.nocheck }}" == "true" ]; then
            NOCHECK_ARG="--nocheck"
          fi
          echo "flags=$FLAGS" >> $GITHUB_OUTPUT
          echo "nocheck_arg=$NOCHECK_ARG" >> $GITHUB_OUTPUT
      - name: Run checkReadyForStable
        id: run_check_ready_for_stable
        run: node checks/checkReadyForStable/checkReadyForStable.js ${{ steps.trim_params.outputs.flags }} ${{ steps.trim_params.outputs.nocheck_arg }}
        env:
          OWN_GITHUB_TOKEN: ${{ secrets.OWN_GITHUB_TOKEN }}
          IOBBOT_GITHUB_TOKEN: ${{ secrets.IOBBOT_GITHUB_TOKEN }}
      - name: Prepare report mail metadata
        id: report_mail_meta
        run: echo "subject_date=$(date -u +'%d.%m.%Y')" >> $GITHUB_OUTPUT
      - name: Send summary report mail
        if: ${{ github.event.inputs.noemail != 'true' }}
        uses: dawidd6/action-send-mail@v18
        with:
          server_address: mail.gmx.net
          server_port: 465
          secure: true
          username: iobroker-bot@gmx.at
          password: ${{ secrets.IOBBOT_GMXMAIL }}
          subject: ReadyForStable Summary Report ${{ steps.report_mail_meta.outputs.subject_date }}
          to: iobroker-bot@gmx.at
          from: ioBroker Bot <iobroker-bot@gmx.at>
          body: ${{ steps.run_check_ready_for_stable.outputs.report_body }}
          html_body: ${{ steps.run_check_ready_for_stable.outputs.html_report_body }}
